services:
  postgres:
    image: postgres
    restart: always
    container_name: postgres_container
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=helpdesk_db
volumes:
  postgres_volume:

