spring:
  application:
    name: helpdesk
  jpa:
    show-sql: true
  datasource:
    url: ${DB_CONNECTION_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
jwt:
  secret: ${JWT_SECRET}